### ISSUE TITLE
error of compilation of sedInterFoam

### ISSUE THREAD

**Issue by charithaRdissanayaka** [mathieu7an/sedInterFoam#1]
Hello sir,

I installed OpenFoam-2.1.x and waves2Foam.
Then I started to install sedInterFoam fllowing the steps given in Readme file.

But I observe following error and compilation terminated.

In file included from sedInterFoam.C:45:0:
../TurbulenceModels/turbulenceModels/lnInclude/sedIncompressibleTurbulenceModel.H:44:29: fatal error: TurbulenceModel.H: No such file or directory
 #include "TurbulenceModel.H"
                             ^
compilation terminated.
sedInterFoam.dep:655: recipe for target 'Make/linux64Gcc48DPOpt/sedInterFoam.o' failed
make: *** [Make/linux64Gcc48DPOpt/sedInterFoam.o] Error 1
[log-make.txt](https://github.com/user-attachments/files/16864934/log-make.txt)

Please check the attached log.make file. your kind reply is highly appreciated.

**Comment by CyrilleBonamy** [comment]
Hello,

I've just updated waves2foam and sedinterfoam to be compatible with openfoam 2406.

And now, I propose to try to create a version every year (related to the year's version of openfoam).

Try updating your openfoam environment and compiling waves2foam and sedinterfoam (as Continuous Integration does).
Feel free to check the installation process in the Continuous Integration file: `.github/workflows/build.yml`

Best regards

**Comment by charithaRdissanayaka** [comment]
Hello Professor Cyrille.

Do you have any example case done based on the timeVaryingMappedFixedField in sedInterFoam?
