### ISSUE TITLE
sedInterFoam with OpenFOAM v2312 and waves2Foam

### ISSUE THREAD

**Issue by benjaminb115** [mathieu7an/sedInterFoam#2]
Hello,

I am currently using OpenFOAM v2312 along with the waves2Foam library for a project involving sediment transport simulations. I am interested in using the sedInterFoam solver from this repository. Could you please confirm if sedInterFoam is compatible with OpenFOAM v2312 or any advanced OpenFOAM versions? Also, are there any additional considerations or dependencies that I should be aware of before attempting to integrate it into my workflow?

Thank you for your time and assistance.

Best regards,
Benjamin

**Comment by CyrilleBonamy** [comment]
Hello Benjamin,

Nice to see you here! 

I'm not sure if older versions of sedinterfoam are compatible with openfoam 2312.
I've just updated waves2foam and sedinterfoam to be compatible with openfoam 2406.

And now, I propose to try to create a version every year (related to the year's version of openfoam).

Try updating your openfoam environment and compiling waves2foam and sedinterfoam (as Continuous Integration does).
Feel free to check the installation process in the Continuous Integration file: .github/workflows/build.yml

Best regards
